<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JavaScript - Error handling with promises</title>
</head>
<body>
    <h3>JavaScript - Error handling with promises</h3>

    <script type="text/javascript">
        // <!-- ðŸ‘‰ part 1  -->
        // function getUserById(id){
        //     if(typeof id !== "number" || id<0){
        //         throw new Error("Invalid ID number");
        //     }
        //     return new Promise((resolve, reject) => {
        //         resolve({
        //             id: id,
        //             userName: 'admin'
        //         })
        //     })
        // }

        // getUserById('faf')
        // .then(user => console.log({ id: user.id,userName: user.userName}))
        // .catch(error => console.log(error));

        // <!-- ðŸ‘‰ part 2  -->
        let userAuthorized = true;
        function getUserById(id){
            if(!userAuthorized){
                throw new Error("User is not Authorized");
            }
            return new Promise((resolve,reject) => {
                resolve({
                    id: id,
                    userName: 'admin'
                })
            })
        }

        try {
            getUserById(7).then(user => console.log(user.userName))
            .catch(error => console.log(`Caught by .catch ${error}`))
        } catch (e) {
            console.log(`Caught by try/catch ${e}`);
        }


    </script>
</body>
</html>